# GoReleaser configuration for Izanami CLI
# See https://goreleaser.com for documentation

version: 2

before:
  hooks:
    # Ensure dependencies are up to date
    - go mod tidy
    # Run tests
    - go test ./...

builds:
  - id: iz
    main: ./cmd/iz
    binary: iz
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    # Ignore Windows ARM64 (not commonly used)
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X github.com/webskin/izanami-go-cli/internal/cmd.Version={{.Version}}
      - -X github.com/webskin/izanami-go-cli/internal/cmd.GitCommit={{.Commit}}
      - -X github.com/webskin/izanami-go-cli/internal/cmd.BuildDate={{.Date}}

archives:
  - id: iz-archive
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE*

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - Merge pull request
      - Merge branch
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: "Bug fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: Others
      order: 999

release:
  github:
    owner: webskin
    name: izanami-go-cli
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}} v{{.Version}}"

# Homebrew tap (optional - uncomment and configure if you want Homebrew support)
# brews:
#   - name: iz
#     repository:
#       owner: webskin
#       name: homebrew-tap
#     folder: Formula
#     homepage: https://github.com/webskin/izanami-go-cli
#     description: "Cross-platform CLI client for Izanami feature flags"
#     license: MIT
#     install: |
#       bin.install "iz"
#       bash_completion.install "completions/iz.bash" => "iz"
#       zsh_completion.install "completions/_iz" => "_iz"
#       fish_completion.install "completions/iz.fish"

# Docker images (optional - uncomment if you want Docker support)
# dockers:
#   - image_templates:
#       - "ghcr.io/webskin/izanami-cli:{{ .Tag }}"
#       - "ghcr.io/webskin/izanami-cli:v{{ .Major }}"
#       - "ghcr.io/webskin/izanami-cli:v{{ .Major }}.{{ .Minor }}"
#       - "ghcr.io/webskin/izanami-cli:latest"
#     dockerfile: Dockerfile
#     build_flag_templates:
#       - "--pull"
#       - "--label=org.opencontainers.image.created={{.Date}}"
#       - "--label=org.opencontainers.image.title={{.ProjectName}}"
#       - "--label=org.opencontainers.image.revision={{.FullCommit}}"
#       - "--label=org.opencontainers.image.version={{.Version}}"
