# GoReleaser configuration for Izanami Go CLI
# Documentation: https://goreleaser.com

version: 2

before:
  hooks:
    # Run tests before building
    - go test ./...
    # Tidy dependencies
    - go mod tidy

builds:
  - id: iz
    main: ./cmd/iz
    binary: iz
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    # Ignore ARM64 for Windows (not commonly used)
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X 'github.com/webskin/izanami-go-cli/internal/cmd.Version={{.Version}}'
      - -X 'github.com/webskin/izanami-go-cli/internal/cmd.GitCommit={{.Commit}}'
      - -X 'github.com/webskin/izanami-go-cli/internal/cmd.BuildDate={{.Date}}'

archives:
  - id: default
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    ids:
      - iz
    files:
      - README.md
      - LICENSE*
      - CHANGELOG.md

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^build:'
      - Merge pull request
      - Merge branch
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: 'Bug Fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: 'Performance Improvements'
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: 'Refactorings'
      regexp: '^.*?refactor(\([[:word:]]+\))??!?:.+$'
      order: 3
    - title: Others
      order: 999

release:
  github:
    owner: webskin
    name: izanami-go-cli
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## Izanami Go CLI {{ .Tag }}

    ### Installation

    Download the appropriate binary for your platform below, extract it, and add it to your PATH.

    #### Quick Install (Linux/macOS)

    ```bash
    # Linux AMD64
    curl -L https://github.com/webskin/izanami-go-cli/releases/download/{{ .Tag }}/izanami-go-cli_{{ .Version }}_linux_x86_64.tar.gz | tar xz
    sudo mv iz /usr/local/bin/

    # macOS AMD64 (Intel)
    curl -L https://github.com/webskin/izanami-go-cli/releases/download/{{ .Tag }}/izanami-go-cli_{{ .Version }}_darwin_x86_64.tar.gz | tar xz
    sudo mv iz /usr/local/bin/

    # macOS ARM64 (Apple Silicon)
    curl -L https://github.com/webskin/izanami-go-cli/releases/download/{{ .Tag }}/izanami-go-cli_{{ .Version }}_darwin_arm64.tar.gz | tar xz
    sudo mv iz /usr/local/bin/
    ```

    ### Verify Installation

    ```bash
    iz version
    ```
  footer: |
    **Full Changelog**: https://github.com/webskin/izanami-go-cli/compare/{{ .PreviousTag }}...{{ .Tag }}

    ---

    🤖 Built with [GoReleaser](https://goreleaser.com)
